'use strict';
// All sprite art lives here as pixel strings, authored facing RIGHT.
// Char legend:  . transparent  K near-black  P suit color  D dark cloth
//               S skin  G belt/gear  W white
// Each frame: { a: anchor column (feet center), r: rows top->bottom }.
// Rows may be short (padded right) and frames may be short (anchored at feet).
// Art pixels are baked at 2x, so a 21-row frame stands ~42 screen px tall.

const NINJA_FRAMES = {

  idle_a: { a: 7, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '...DDDD',
    '..DDDDDD.SS',
    '.SDDDDDD.SS',
    '.S..DPPPDS',
    '.SS.DPPPD',
    '....DPPPD',
    '....DDDDD',
    '....GGGG',
    '...PPPPPP',
    '...PPP.PPP',
    '..PPP...PPP',
    '..PPP...PPP',
    '..PP.....PP',
    '..PP.....PP',
    '..PP.....PP',
    '..DD.....DD',
    '.KKK.....KKK',
  ]},

  idle_b: { a: 7, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '...DDDD',
    '..DDDDDD',
    '.SDDDDDD.SS',
    '.S..DPPPDSS',
    '.SS.DPPPDS',
    '....DPPPD',
    '....DDDDD',
    '....GGGG',
    '...PPPPPP',
    '...PPP.PPP',
    '..PPP...PPP',
    '..PPP...PPP',
    '..PP.....PP',
    '..PP.....PP',
    '..PP.....PP',
    '..DD.....DD',
    '.KKK.....KKK',
  ]},

  walk_a: { a: 7, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '...DDDD',
    '..DDDDDD.SS',
    '.SDDDDDD.SS',
    '.S..DPPPDS',
    '.SS.DPPPD',
    '....DPPPD',
    '....DDDDD',
    '....GGGG',
    '...PPPPPP',
    '..PPPP.PPP',
    '.PPP....PPP',
    '.PPP.....PPP',
    '.PP.......PP',
    '.PP.......PP',
    '.DD.......DD',
    'KKK.......KKK',
  ]},

  walk_b: { a: 7, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '...DDDD',
    '..DDDDDD.SS',
    '.SDDDDDD.SS',
    '.S..DPPPDS',
    '.SS.DPPPD',
    '....DPPPD',
    '....DDDDD',
    '....GGGG',
    '...PPPPPP',
    '...PPPPPP',
    '...PPPPPP',
    '...PPP.PP',
    '...PPP.PP',
    '...PP..PP',
    '...PP..PP',
    '...DD..DD',
    '..KKK..KKK',
  ]},

  jump: { a: 6, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '..DDDDDD.SS',
    '.SDDDDDDSS',
    '.S.DPPPD',
    '.SSDPPPD',
    '...GGGG',
    '...PPPPPP',
    '..PPPPPPPP',
    '..PPP..PPP',
    '..DD....DD',
    '.KKK...KKK',
  ]},

  jump_kick: { a: 6, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '..DDDDDD.SS',
    '.SDDDDDDSS',
    '.S.DPPPD',
    '.SSDPPPD',
    '...GGGG.PPP',
    '...PPPPPPPPPP',
    '..PPP.....PPKKK',
    '..KKK......KKK',
  ]},

  crouch: { a: 6, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '..DDDDDD.SS',
    '.SDDDDDD.SS',
    '.S.DPPPPDS',
    '.SS.DPPPD',
    '..GGGGGG',
    '.PPPPPPPPP',
    '.PPP....PPP',
    'KKK......KKK',
  ]},

  crouch_punch: { a: 6, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '..DDDDDD',
    '.SDDDDDDSSSSSS',
    '.S.DPPPPD...SS',
    '.SS.DPPPD',
    '..GGGGGG',
    '.PPPPPPPPP',
    '.PPP....PPP',
    'KKK......KKK',
  ]},

  crouch_kick: { a: 6, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '..DDDDDD.SS',
    '.SDDDDDD.SS',
    '.S.DPPPPDS',
    '.SS.DPPPD',
    '..GGGGGG',
    '.PPPP..PPPPPPPKK',
    '.PPPP',
    'KKKK',
  ]},

  block: { a: 7, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '...DDDD',
    '..DDSSSS',
    '..DSSSSS',
    '..DDSSSS',
    '...DPPPD',
    '....DDDD',
    '....GGGG',
    '...PPPPPP',
    '...PPP.PPP',
    '..PPP...PPP',
    '..PPP...PPP',
    '..PP.....PP',
    '..PP.....PP',
    '..PP.....PP',
    '..DD.....DD',
    '.KKK.....KKK',
  ]},

  block_crouch: { a: 6, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '..DSSSSS',
    '..DSSSSS',
    '..DDPPPD',
    '..GGGGGG',
    '.PPPPPPPPP',
    '.PPP....PPP',
    'KKK......KKK',
  ]},

  punch_wind: { a: 7, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '...DDDD',
    '..DDDDDD',
    '.SDDDDDDSS',
    '.S.DPPPDSS',
    '.SS.DPPPD',
    '....DPPPD',
    '....DDDDD',
    '....GGGG',
    '...PPPPPP',
    '...PPP.PPP',
    '..PPP...PPP',
    '..PPP...PPP',
    '..PP.....PP',
    '..PP.....PP',
    '..PP.....PP',
    '..DD.....DD',
    '.KKK.....KKK',
  ]},

  hpunch: { a: 7, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '...DDDD',
    '..DDDDDDSSSSSSSS',
    '.SDDDDDD',
    '.S..DPPPD',
    '.SS.DPPPD',
    '....DPPPD',
    '....DDDDD',
    '....GGGG',
    '...PPPPPP',
    '..PPPP.PPP',
    '.PPP....PPP',
    '.PPP.....PPP',
    '.PP.......PP',
    '.PP.......PP',
    '.DD.......DD',
    'KKK.......KKK',
  ]},

  lpunch: { a: 7, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '...DDDD',
    '..DDDDDD',
    '.SDDDDDD',
    '.S..DPPPDSSSSSS',
    '.SS.DPPPD',
    '....DPPPD',
    '....DDDDD',
    '....GGGG',
    '...PPPPPP',
    '...PPP.PPP',
    '..PPP...PPP',
    '..PPP...PPP',
    '..PP.....PP',
    '..PP.....PP',
    '..PP.....PP',
    '..DD.....DD',
    '.KKK.....KKK',
  ]},

  kick_wind: { a: 6, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '...DDDD',
    '..DDDDDD.SS',
    '.SDDDDDD.SS',
    '.S..DPPPDS',
    '.SS.DPPPD',
    '....DPPPD',
    '....DDDDD',
    '....GGGG',
    '...PPPPPP',
    '...PPP.PPPP',
    '...PPP..KKK',
    '...PP',
    '...PP',
    '...PP',
    '...PP',
    '...DD',
    '..KKK',
  ]},

  hkick: { a: 6, r: [
    '..PPPP',
    '.PPPPPP',
    '.PSSSKP',
    '.PPPPPP',
    '..DDDD.........KK',
    '.SDDDDD......PPKK',
    '.S.DPPPD...PPP',
    '.SS.DPPPD.PPP',
    '....DPPPDPPP',
    '....DDDDDPP',
    '....GGGGG',
    '....PPPPP',
    '....PPP',
    '....PPP',
    '....PP',
    '....PP',
    '....PP',
    '....DD',
    '...KKK',
  ]},

  lkick: { a: 6, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '...DDDD',
    '..DDDDDD.SS',
    '.SDDDDDD.SS',
    '.S..DPPPDS',
    '.SS.DPPPD',
    '....DPPPD',
    '....DDDDD',
    '....GGGG',
    '...PPPPPPPPPPPKKK',
    '...PPP',
    '...PPP',
    '...PP',
    '...PP',
    '...PP',
    '...DD',
    '..KKK',
  ]},

  sweep: { a: 5, r: [
    '..PPPP',
    '.PPPPPP',
    '.PSSSKP',
    '.PPPPPP',
    '.SDDDDD',
    '.S.DPPPD',
    '..DPPPD',
    '.GGGGG',
    '.PPPP..PPPPPPPPKKK',
    '.PPPP',
    'KKKK',
  ]},

  upc_wind: { a: 6, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '..DDDDDD',
    '.SDDDDDD',
    '.S.DPPPPD',
    '.SSDPPPPD',
    '..GGGGGG',
    '.PPPPPPPPP',
    '.PPP....PPP',
    'KKK......KKK',
  ]},

  upc_hit: { a: 7, r: [
    '.........SS',
    '.........SS',
    '....PPPP.S',
    '...PPPPPPS',
    '...PSSSKPS',
    '...PPPPPPS',
    '....DDDDSS',
    '...DDDDDDD',
    '..SDDDDDD',
    '..S.DPPPD',
    '..SSDPPPD',
    '.....GGGG',
    '....PPPPPP',
    '....PPP.PPP',
    '...PPP...PPP',
    '...PPP....PPP',
    '...PP......PP',
    '...PP......PP',
    '...DD......DD',
    '..KKK.....KKK',
  ]},

  hit: { a: 7, r: [
    '.PPPP',
    'PPPPPP',
    'PSKSSP',
    'PPPPPP',
    '.DDDDD',
    'SSDDDDDD.SS',
    '..DDDDDD.S',
    '...DPPPDS',
    '...DPPPD',
    '...DDDDD',
    '...GGGG',
    '...PPPPPP',
    '..PPP.PPP',
    '..PPP..PPP',
    '..PP....PP',
    '..PP....PPP',
    '..DD.....DD',
    '.KKK....KKK',
  ]},

  juggle: { a: 8, r: [
    '...SS...PPP..KK',
    '....DDDDPPP..KK',
    '.PPPPDDDDDPPPPP',
    '.PSSSPPPPDDD',
    '.PPPP.SS.GG',
  ]},

  down: { a: 9, r: [
    '.PPPP',
    'PPSSPP.DDDDPPPPPKK',
    'PPPPPPGGDDDPPPPPKK',
  ]},

  win: { a: 7, r: [
    '.SS.......SS',
    '.S.........S',
    '.S..PPPP...S',
    '.S.PPPPPP..S',
    '.S.PSSSSP..S',
    '.SDPPPPPPDS',
    '..DDDDDDDD',
    '...DPPPPD',
    '...DPPPPD',
    '...DDDDD',
    '...GGGG',
    '..PPPPPP',
    '..PPP.PPP',
    '.PPP...PPP',
    '.PPP...PPP',
    '.PP.....PP',
    '.PP.....PP',
    '.PP.....PP',
    '.DD.....DD',
    'KKK.....KKK',
  ]},

  // horizontal flying dash (VOLTAN's torpedo) -- body floats above the ground
  torpedo: { a: 8, r: [
    '...........PPPP',
    'KKPPPP.DDDDPPSKP',
    '.KKPPPDDDDDPPPPPSS',
    '......GGG.PPPP',
    '.',
    '.',
    '.',
    '.',
    '.',
  ]},

  // FINISH THEM stance: slumped, arms hanging, crossed-out eyes
  dazed: { a: 6, r: [
    '...PPPP',
    '..PPPPPP',
    '..PKSSKP',
    '..PPPPPP',
    '...DDDD',
    '..DDDDDD',
    '.SDDDDDDS',
    '.S.DPPPD.S',
    '.S.DPPPD.S',
    '...DPPPD',
    '...DDDDD',
    '...GGGG',
    '...PPPPP',
    '...PPP.PP',
    '..PPP..PP',
    '..PPP..PPP',
    '..PP....PP',
    '..PP....PP',
    '..DD....DD',
    '.KKK...KKK',
  ]},

  throw_proj: { a: 7, r: [
    '...PPPP',
    '..PPPPPP',
    '..PSSSKP',
    '..PPPPPP',
    '...DDDD',
    '..DDDDDDSSSSS',
    '..DDDDDDSSSSS',
    '....DPPPD',
    '....DPPPD',
    '....DDDDD',
    '....GGGG',
    '...PPPPPP',
    '..PPPP.PPP',
    '.PPP....PPP',
    '.PPP.....PPP',
    '.PP.......PP',
    '.PP.......PP',
    '.DD.......DD',
    'KKK.......KKK',
  ]},
};

// ---- GORRUK: the four-armed boss. Bigger grid (<=26 wide), own frame set.
// Upper arm pair hangs from the huge shoulders; lower pair guards the waist.
const GORRUK_FRAMES = {

  idle_a: { a: 12, r: [
    '...........SSSS',
    '..........SSSSSS',
    '..........SKSSKS',
    '..........SWSSWS',
    '...........SSSS',
    '...SSSSSSSSSSSSSSSSSS',
    '..SSSSSSSSSSSSSSSSSSSS',
    '..SSSS.PPPPPPPPPP.SSSS',
    '..SSSS.PPPPPPPPPP.SSSS',
    '..SSS..PPPPPPPPPP..SSS',
    '..SSS..PPPPPPPPPP..SSS',
    '.SSSS..PPPPPPPPPP..SSSS',
    '.SSSS.SSPPPPPPPPSS.SSSS',
    '..SS..SSSPPPPPPSSS..SS',
    '......SSS.PPPP.SSS',
    '.....SSSS.GGGG.SSSS',
    '........GGGGGGGG',
    '.......PPPPPPPPPP',
    '.......PPPP..PPPP',
    '......PPPP....PPPP',
    '......PPPP....PPPP',
    '......PPP......PPP',
    '......PPP......PPP',
    '......PPP......PPP',
    '......DDD......DDD',
    '.....KKKK......KKKK',
  ]},

  idle_b: { a: 12, r: [
    '...........SSSS',
    '..........SSSSSS',
    '..........SKSSKS',
    '..........SWSSWS',
    '...........SSSS',
    '....SSSSSSSSSSSSSSSS',
    '..SSSSSSSSSSSSSSSSSSSS',
    '..SSSS.PPPPPPPPPP.SSSS',
    '..SSSS.PPPPPPPPPP.SSSS',
    '..SSS..PPPPPPPPPP..SSS',
    '.SSSS..PPPPPPPPPP..SSSS',
    '.SSSS..PPPPPPPPPP..SSSS',
    '..SS..SSPPPPPPPPSS..SS',
    '......SSSPPPPPPSSS',
    '......SSS.PPPP.SSS',
    '.....SSSS.GGGG.SSSS',
    '........GGGGGGGG',
    '.......PPPPPPPPPP',
    '.......PPPP..PPPP',
    '......PPPP....PPPP',
    '......PPPP....PPPP',
    '......PPP......PPP',
    '......PPP......PPP',
    '......PPP......PPP',
    '......DDD......DDD',
    '.....KKKK......KKKK',
  ]},

  walk_a: { a: 12, r: [
    '...........SSSS',
    '..........SSSSSS',
    '..........SKSSKS',
    '..........SWSSWS',
    '...........SSSS',
    '...SSSSSSSSSSSSSSSSSS',
    '..SSSSSSSSSSSSSSSSSSSS',
    '..SSSS.PPPPPPPPPP.SSSS',
    '..SSSS.PPPPPPPPPP.SSSS',
    '..SSS..PPPPPPPPPP..SSS',
    '..SSS..PPPPPPPPPP..SSS',
    '.SSSS..PPPPPPPPPP..SSSS',
    '.SSSS.SSPPPPPPPPSS.SSSS',
    '..SS..SSSPPPPPPSSS..SS',
    '......SSS.PPPP.SSS',
    '.....SSSS.GGGG.SSSS',
    '........GGGGGGGG',
    '.......PPPPPPPPPP',
    '......PPPPP..PPPPP',
    '.....PPPP......PPPP',
    '....PPPP........PPPP',
    '....PPP..........PPP',
    '....PPP..........PPP',
    '....PPP..........PPP',
    '....DDD..........DDD',
    '...KKKK..........KKKK',
  ]},

  walk_b: { a: 12, r: [
    '...........SSSS',
    '..........SSSSSS',
    '..........SKSSKS',
    '..........SWSSWS',
    '...........SSSS',
    '...SSSSSSSSSSSSSSSSSS',
    '..SSSSSSSSSSSSSSSSSSSS',
    '..SSSS.PPPPPPPPPP.SSSS',
    '..SSSS.PPPPPPPPPP.SSSS',
    '..SSS..PPPPPPPPPP..SSS',
    '..SSS..PPPPPPPPPP..SSS',
    '.SSSS..PPPPPPPPPP..SSSS',
    '.SSSS.SSPPPPPPPPSS.SSSS',
    '..SS..SSSPPPPPPSSS..SS',
    '......SSS.PPPP.SSS',
    '.....SSSS.GGGG.SSSS',
    '........GGGGGGGG',
    '.......PPPPPPPPPP',
    '.......PPPP..PPPP',
    '.......PPPP..PPPP',
    '.......PPP....PPP',
    '.......PPP....PPP',
    '.......PPP....PPP',
    '.......PPP....PPP',
    '.......DDD....DDD',
    '......KKKK....KKKK',
  ]},

  punch_wind: { a: 12, r: [
    '...........SSSS',
    '..........SSSSSS',
    '..........SKSSKS',
    '..........SWSSWS',
    '...........SSSS',
    '...SSSSSSSSSSSSSSSS',
    '..SSSSSSSSSSSSSSSSSSSS',
    '..SSSS.PPPPPPPPPP.SSSS',
    '..SSSS.PPPPPPPPPPSSSS',
    '..SSS..PPPPPPPPPPSSS',
    '..SSS..PPPPPPPPPP',
    '.SSSS..PPPPPPPPPP',
    '.SSSS.SSPPPPPPPPSS',
    '..SS..SSSPPPPPPSSS',
    '......SSS.PPPP.SSS',
    '.....SSSS.GGGG.SSSS',
    '........GGGGGGGG',
    '.......PPPPPPPPPP',
    '.......PPPP..PPPP',
    '......PPPP....PPPP',
    '......PPPP....PPPP',
    '......PPP......PPP',
    '......PPP......PPP',
    '......PPP......PPP',
    '......DDD......DDD',
    '.....KKKK......KKKK',
  ]},

  punch: { a: 12, r: [
    '...........SSSS',
    '..........SSSSSS',
    '..........SKSSKS',
    '..........SWSSWS',
    '...........SSSS',
    '...SSSSSSSSSSSSSSSSSS',
    '..SSSSSSSSSSSSSSSSSSSSSSSS',
    '..SSSS.PPPPPPPPPPSSSSSSSS',
    '..SSSS.PPPPPPPPPP',
    '..SSS..PPPPPPPPPP',
    '..SSS..PPPPPPPPPP',
    '.SSSS..PPPPPPPPPP',
    '.SSSS.SSPPPPPPPPSS',
    '..SS..SSSPPPPPPSSS',
    '......SSS.PPPP.SSS',
    '.....SSSS.GGGG.SSSS',
    '........GGGGGGGG',
    '.......PPPPPPPPPP',
    '......PPPPP..PPPPP',
    '.....PPPP......PPPP',
    '.....PPPP......PPPP',
    '.....PPP........PPP',
    '.....PPP........PPP',
    '.....PPP........PPP',
    '.....DDD........DDD',
    '....KKKK........KKKK',
  ]},

  slam_wind: { a: 12, r: [
    '...SSS............SSS',
    '...SSSS..........SSSS',
    '....SSS..........SSS',
    '....SSS...SSSS...SSS',
    '....SSS..SSSSSS..SSS',
    '....SSSS.SKSSKS.SSSS',
    '.....SSS.SWSSWS.SSS',
    '......SSS.SSSS.SSS',
    '...SSSSSSSSSSSSSSSSSS',
    '..SSSSSSSSSSSSSSSSSSSS',
    '..SSSS.PPPPPPPPPP.SSSS',
    '.......PPPPPPPPPP',
    '.......PPPPPPPPPP',
    '......SSPPPPPPPPSS',
    '......SSSPPPPPPSSS',
    '......SSS.PPPP.SSS',
    '.....SSSS.GGGG.SSSS',
    '........GGGGGGGG',
    '.......PPPPPPPPPP',
    '.......PPPP..PPPP',
    '......PPPP....PPPP',
    '......PPPP....PPPP',
    '......PPP......PPP',
    '......PPP......PPP',
    '......PPP......PPP',
    '......DDD......DDD',
    '.....KKKK......KKKK',
  ]},

  slam: { a: 12, r: [
    '...........SSSS',
    '..........SSSSSS',
    '..........SKSSKS',
    '..........SWSSWS',
    '...........SSSS',
    '....SSSSSSSSSSSSSSSS',
    '...SSSSSSSSSSSSSSSSSS',
    '...SSS.PPPPPPPPPP.SSS',
    '.......PPPPPPPPPPSSSS',
    '.......PPPPPPPPPP.SSSS',
    '.......PPPPPPPPPP..SSSS',
    '......SSPPPPPPPPSS..SSSS',
    '......SSSPPPPPPSSS..SSSS',
    '......SSS.PPPP.SSSS.SSSS',
    '.....SSSS.GGGG..SSSSSSS',
    '........GGGGGGGG..SSSS',
    '.......PPPPPPPPPP',
    '......PPPPP..PPPPP',
    '.....PPPP......PPPP',
    '.....PPPP......PPPP',
    '.....PPP........PPP',
    '.....PPP........PPP',
    '.....PPP........PPP',
    '.....DDD........DDD',
    '....KKKK........KKKK',
  ]},

  block: { a: 12, r: [
    '...........SSSS',
    '..........SSSSSS',
    '..........SKSSKS',
    '..........SWSSWS',
    '...........SSSS',
    '...SSSSSSSSSSSSSSSSSS',
    '..SSSSSSSSSSSSSSSSSSSS',
    '..SSSS.SSSSSSSSSS.SSSS',
    '..SSSS.SSSSSSSSSS.SSSS',
    '..SSS..PSSSSSSSSP..SSS',
    '..SSS..PPSSSSSSPP..SSS',
    '.SSSS..PPPPPPPPPP..SSSS',
    '.SSSS.SSPPPPPPPPSS.SSSS',
    '..SS..SSSPPPPPPSSS..SS',
    '......SSS.PPPP.SSS',
    '.....SSSS.GGGG.SSSS',
    '........GGGGGGGG',
    '.......PPPPPPPPPP',
    '.......PPPP..PPPP',
    '......PPPP....PPPP',
    '......PPPP....PPPP',
    '......PPP......PPP',
    '......PPP......PPP',
    '......PPP......PPP',
    '......DDD......DDD',
    '.....KKKK......KKKK',
  ]},

  hit: { a: 12, r: [
    '........SSSS',
    '.......SSSSSS',
    '.......SKSKSS',
    '.......SWSSWS',
    '........SSSS',
    '..SSSSSSSSSSSSSSSSS',
    '.SSSSSSSSSSSSSSSSSSSS',
    '.SSSS.PPPPPPPPPP.SSSS',
    '.SSSS.PPPPPPPPPP.SSSS',
    '.SSS..PPPPPPPPPP..SSS',
    '.SSS..PPPPPPPPPP..SSS',
    'SSSS..PPPPPPPPPP..SSSS',
    'SSSS.SSPPPPPPPPSS.SSSS',
    '.SS..SSSPPPPPPSSS..SS',
    '.....SSS.PPPP.SSS',
    '....SSSS.GGGG.SSSS',
    '.......GGGGGGGG',
    '......PPPPPPPPPP',
    '......PPPP..PPPP',
    '.....PPPP....PPPPP',
    '.....PPPP.....PPPP',
    '.....PPP.......PPP',
    '.....PPP.......PPP',
    '.....PPP.......PPP',
    '.....DDD.......DDD',
    '....KKKK......KKKKK',
  ]},

  down: { a: 13, r: [
    '....SSSS',
    '...SSSSSS..SSSSSSSSSSS',
    '..SSSSSSSSPPPPPPPPPPPPPPKK',
    '.SSSSSSSSSPPPPPPPPPPPPPKKK',
    '...SSSS.GGGGGG.SSSSSS',
  ]},

  win: { a: 12, r: [
    '.SSS.................SSS',
    '.SSSS...............SSSS',
    '..SSS....SSSS.......SSS',
    '..SSS...SSSSSS......SSS',
    'SS.SSS..SKSSKS..SSS.SS',
    'SS..SSS.SWSSWS.SSS..SS',
    '.SS..SSS.SSSS.SSS..SS',
    '..SS..SSSSSSSSSS..SS',
    '...SSSSSSSSSSSSSSSS',
    '..SSSSSSSSSSSSSSSSSS',
    '..SS...PPPPPPPPPP...SS',
    '.......PPPPPPPPPP',
    '.......PPPPPPPPPP',
    '.......PPPPPPPPPP',
    '........PPPPPPPP',
    '.....SSSS.GGGG.SSSS',
    '........GGGGGGGG',
    '.......PPPPPPPPPP',
    '.......PPPP..PPPP',
    '......PPPP....PPPP',
    '......PPPP....PPPP',
    '......PPP......PPP',
    '......PPP......PPP',
    '......PPP......PPP',
    '......DDD......DDD',
    '.....KKKK......KKKK',
  ]},
};

// ---- portraits (select + ladder screens) ----
const NINJA_PORTRAIT = { a: 0, r: [
  '..PPPPPP..',
  '.PPPPPPPP.',
  '.PPPPPPPP.',
  '.PSSSSSSP.',
  '.PSKSSKSP.',
  '.PSSSSSSP.',
  '.PPPPPPPP.',
  '.PPPPPPPP.',
  '.DDPPPPDD.',
  '.DDDDDDDD.',
]};

// thunder god: wide hat brim, glowing white eyes
const VOLTAN_PORTRAIT = { a: 0, r: [
  '....PP....',
  '..PPPPPP..',
  'PPPPPPPPPP',
  '..SSSSSS..',
  '..SWSSWS..',
  '..SSSSSS..',
  '..SSSSSS..',
  '..DDDDDD..',
  '.DDDDDDDD.',
  '.DDDDDDDD.',
]};

// soldier: buzz cut + headband
const STRIKER_PORTRAIT = { a: 0, r: [
  '..KKKKKK..',
  '.KKKKKKKK.',
  '.PPPPPPPP.',
  '.SSSSSSSS.',
  '.SKSSSSKS.',
  '.SSSSSSSS.',
  '.SSSSSSSS.',
  '.SSDDDDSS.',
  '.DDDDDDDD.',
  '.DDDDDDDD.',
]};

// the boss: heavy brow, tusks
const GORRUK_PORTRAIT = { a: 0, r: [
  '..SSSSSS..',
  '.SSSSSSSS.',
  'SSKSSSSKSS',
  'SSWSSSSWSS',
  'SSSSSSSSSS',
  'SWSSSSSSWS',
  '.SSSSSSSS.',
  '.SSSSSSSS.',
  '.SPPPPPPS.',
  '.PPPPPPPP.',
]};

// portraitArt key on a character def -> portrait frame (default: ninja hood)
const PORTRAIT_ART = {
  default: NINJA_PORTRAIT,
  voltan: VOLTAN_PORTRAIT,
  striker: STRIKER_PORTRAIT,
  gorruk: GORRUK_PORTRAIT,
};

// ---- projectiles ----
const PROJ_FRAMES = {
  iceball_a: { a: 2, r: [
    '.CC.',
    'CWWC',
    'CWWB',
    '.CB.',
  ]},
  iceball_b: { a: 2, r: [
    '.CB.',
    'BWWC',
    'CWWC',
    '.CC.',
  ]},
  spear: { a: 5, r: [
    '........W.',
    'GGGGGGGGWW',
    '........W.',
  ]},
  ring_a: { a: 3, r: [
    '.RRRR.',
    'RY..YR',
    'RY..YR',
    '.RRRR.',
  ]},
  ring_b: { a: 3, r: [
    '.RYRR.',
    'RR..RR',
    'RR..RR',
    '.RRYR.',
  ]},
};

const PROJ_PALETTE = {
  C: '#7ce0f8', W: '#f0fbff', B: '#2e8cc8', G: '#8a6a3a',
  R: '#48c048', Y: '#d8f8b0',
};

// ---- fighter palettes ----
// Low-saturation, ominous. P is the signature color.
const PALETTES = {
  kiro: {
    P: '#3e6fa8', D: '#23232e', S: '#d6a273', K: '#10101a',
    G: '#6f6f7a', W: '#e8e8f0',
  },
  kiro_alt: {
    P: '#2e8c84', D: '#23232e', S: '#d6a273', K: '#10101a',
    G: '#6f6f7a', W: '#e8e8f0',
  },
  ashkar: {
    P: '#c07a1e', D: '#2e2326', S: '#d6a273', K: '#10101a',
    G: '#6f6f7a', W: '#e8e8f0',
  },
  ashkar_alt: {
    P: '#a83a2e', D: '#2e2326', S: '#d6a273', K: '#10101a',
    G: '#6f6f7a', W: '#e8e8f0',
  },
  voltan: {
    P: '#c8c8d8', D: '#28283a', S: '#d6a273', K: '#10101a',
    G: '#c8a030', W: '#ffffff',
  },
  voltan_alt: {
    P: '#8888c8', D: '#28283a', S: '#d6a273', K: '#10101a',
    G: '#c8a030', W: '#ffffff',
  },
  striker: {
    P: '#4a7a3a', D: '#2a2a22', S: '#d6a273', K: '#10101a',
    G: '#7a6a4a', W: '#e8e8f0',
  },
  striker_alt: {
    P: '#8a8a4a', D: '#2a2a22', S: '#d6a273', K: '#10101a',
    G: '#7a6a4a', W: '#e8e8f0',
  },
  gorruk: {
    P: '#7a2424', D: '#2a2020', S: '#b87848', K: '#140e0e',
    G: '#c8a030', W: '#e8e8f0',
  },
  // frozen overlay palette: everything goes icy
  ice: {
    P: '#a8e0f4', D: '#5a9cc4', S: '#c4ecf8', K: '#3a7ca8',
    G: '#7cc0dc', W: '#ffffff',
  },
  // white silhouette for the 2-frame hit flash
  flash: {
    P: '#ffffff', D: '#ffffff', S: '#ffffff', K: '#ffffff',
    G: '#ffffff', W: '#ffffff',
  },
};
