'use strict';
// Native-resolution fighter art (1 art pixel = 1 screen pixel, no EPX).
// One shared BODY rig supplies the martial-arts poses; each character gets a
// HEAD sprite (matching their select-screen portrait) composited on at bake
// time, plus their own garb palette. Body frames are headless and carry
// hd:[x,y] -- where the head's bottom-center anchor lands.
//
// Body chars: S skin  P garb  p garb speckle (camo blotch on STRIKER)
//             D dark under-suit  G belt/sash  b boots
// Head chars (per character): H hood/hat/hair  M/m mask/bandage  T hat straw
//             d shadowed skin  B beard/headband  C/c bandana  W eyes  k pupil

// ---- torso blocks (rows 0-13: neck, shoulders, arms, belt) ----
const T_GUARD = [
  '............DDD',
  '..........DDDDDDD',
  '.........DDDDDDDDD',
  '.......DDDDDDDDDDDD',
  '......DDDDPPPPPPDDD',
  '.....SDDDPPPPPPPDD.SS',
  '.....SDD.PPPPpPPD.SSS',
  '....SS...PPPPPPPP.SSS',
  '....SS...PPPPpPPPSSS',
  '....SS...DPPPPPPDSS',
  '....SS...DPPPPPPD',
  '....SSS..DDPPPPDD',
  '.....SS...GGGGGG',
  '..........GGGGGG',
];

const T_GUARD_LO = [
  '............DDD',
  '..........DDDDDDD',
  '.........DDDDDDDDD',
  '.......DDDDDDDDDDDD',
  '......DDDDPPPPPPDDD',
  '.....SDDDPPPPPPPDD',
  '.....SDD.PPPPpPPD..SS',
  '....SS...PPPPPPPP.SSS',
  '....SS...PPPPpPPP.SSS',
  '....SS...DPPPPPPDSSS',
  '....SS...DPPPPPPD',
  '....SSS..DDPPPPDD',
  '.....SS...GGGGGG',
  '..........GGGGGG',
];

const T_GUARD_HI = [
  '............DDD',
  '..........DDDDDDD',
  '.........DDDDDDDDD',
  '.......DDDDDDDDDDDD',
  '......DDDDPPPPPPDDD.SS',
  '.....SDDDPPPPPPPDD.SSS',
  '.....SDD.PPPPpPPD..SS',
  '....SS...PPPPPPPPSS',
  '....SS...PPPPpPPPSS',
  '....SS...DPPPPPPD',
  '....SS...DPPPPPPD',
  '....SSS..DDPPPPDD',
  '.....SS...GGGGGG',
  '..........GGGGGG',
];

const T_CHAMBER = [
  '............DDD',
  '..........DDDDDDD',
  '.........DDDDDDDDD',
  '.......DDDDDDDDDDDD',
  '......DDDDPPPPPPDDD',
  '.....SDDDPPPPPPPDDD',
  '.....SDD.PPPPpPPDD',
  '....SS...PPPPPPPPSS',
  '....SS...PPPPpPPSSS',
  '....SS...DPPPPPPSSS',
  '....SS...DPPPPPPD',
  '....SSS..DDPPPPDD',
  '.....SS...GGGGGG',
  '..........GGGGGG',
];

const T_PUNCH_HI = [
  '............DDD',
  '..........DDDDDDD',
  '.........DDDDDDDDD',
  '.......DDDDDDDDDDDD',
  '......DDDDPPPPPPDDDSSSSSSSSSS',
  '.....SDDDPPPPPPPDDSSSSSSSSSSS',
  '.....SDD.PPPPpPPDD',
  '....SS...PPPPPPPP',
  '....SS...PPPPpPPP',
  '....SS...DPPPPPPD',
  '....SS...DPPPPPPD',
  '....SSS..DDPPPPDD',
  '.....SS...GGGGGG',
  '..........GGGGGG',
];

const T_PUNCH_MID = [
  '............DDD',
  '..........DDDDDDD',
  '.........DDDDDDDDD',
  '.......DDDDDDDDDDDD',
  '......DDDDPPPPPPDDD',
  '.....SDDDPPPPPPPDDD',
  '.....SDD.PPPPpPPDD',
  '....SS...PPPPPPPPSSSSSSSSSSS',
  '....SS...PPPPpPPPSSSSSSSSSSS',
  '....SS...DPPPPPPD',
  '....SS...DPPPPPPD',
  '....SSS..DDPPPPDD',
  '.....SS...GGGGGG',
  '..........GGGGGG',
];

const T_PUNCH_FOLLOW = [
  '............DDD',
  '..........DDDDDDD',
  '.........DDDDDDDDD',
  '.......DDDDDDDDDDDD',
  '......DDDDPPPPPPDDD',
  '.....SDDDPPPPPPPDDD',
  '.....SDD.PPPPpPPDDSSS',
  '....SS...PPPPPPPP..SSSS',
  '....SS...PPPPpPPP.....SS',
  '....SS...DPPPPPPD',
  '....SS...DPPPPPPD',
  '....SSS..DDPPPPDD',
  '.....SS...GGGGGG',
  '..........GGGGGG',
];

const T_THROW = [
  '............DDD',
  '..........DDDDDDD',
  '.........DDDDDDDDD',
  '.......DDDDDDDDDDDD',
  '......DDDDPPPPPPDDD',
  '......DDDPPPPPPPDDSSSSSSSS',
  '......DD.PPPPpPPDDSSSSSSSSS',
  '.........PPPPPPPPSSSSSSSSS',
  '.........PPPPpPPPSSSSSSSS',
  '.........DPPPPPPD',
  '.........DPPPPPPD',
  '.........DDPPPPDD',
  '..........GGGGGG',
  '..........GGGGGG',
];

const T_BLOCK = [
  '............DDD',
  '..........DDDDDDD',
  '.........DDDDDDDDD',
  '.......DDDDDDDDDDDD',
  '......DDDDPPPPPPDDD',
  '.....SDDDPPSSSSPDDD',
  '.....SDD.PSSSSSSPDD',
  '....SS...SSSSSSSS',
  '....SS...SSSSSSSS',
  '....SS...PSSSSpSP',
  '....SS...DPPPPPPD',
  '....SSS..DDPPPPDD',
  '.....SS...GGGGGG',
  '..........GGGGGG',
];

const T_HIT = [
  '..........DDD',
  '.........DDDDDDD',
  '.SS......DDDDDDDD',
  '..SS...DDDDDDDDDDD',
  '...SS.DDDDPPPPPDDD.SS',
  '....SSDDDPPPPPPDD.SS',
  '......D.PPPPpPPDDSS',
  '.........PPPPPPPP',
  '.........PPPPpPPP',
  '.........DPPPPPPD',
  '.........DPPPPPPD',
  '.........DDPPPPDD',
  '..........GGGGGG',
  '..........GGGGGG',
];

const T_DAZED = [
  '............DDD',
  '..........DDDDDDD',
  '.........DDDDDDDDD',
  '.......DDDDDDDDDDDD',
  '......DDDDPPPPPPDDD',
  '.....SDDDPPPPPPPDDS',
  '.....SDD.PPPPpPPDDS',
  '....SS...PPPPPPPP.SS',
  '....SS...PPPPpPPP.SS',
  '....SS...DPPPPPPD.SS',
  '....SS...DPPPPPPD.SS',
  '....SSS..DDPPPPDD.SS',
  '.....SS...GGGGGG..S',
  '..........GGGGGG',
];

const T_WIN = [
  '....SS.............SS',
  '....SS.............SS',
  '.....SS...........SS',
  '.....SS...........SS',
  '......SS....DDD..SS',
  '......DDDDDDDDDDDDD',
  '......DDDDPPPPPPDDD',
  '.........PPPPPPPP',
  '.........PPPPpPPP',
  '.........DPPPPPPD',
  '.........DPPPPPPD',
  '.........DDPPPPDD',
  '..........GGGGGG',
  '..........GGGGGG',
];

const T_WIN_B = [
  '......SS..........SS',
  '......SS..........SS',
  '.......SS........SS',
  '.......SS...DDD.SS',
  '........SDDDDDDDS',
  '......DDDDDDDDDDDDD',
  '......DDDDPPPPPPDDD',
  '.........PPPPPPPP',
  '.........PPPPpPPP',
  '.........DPPPPPPD',
  '.........DPPPPPPD',
  '.........DDPPPPDD',
  '..........GGGGGG',
  '..........GGGGGG',
];

// ---- leg blocks (rows 14-31) ----
const L_STAND = [
  '.........PPPPPPPP',
  '.........PPPPPPPP',
  '.........PPPP.PPP',
  '........PPPP..PPPP',
  '........PPPP..PPPP',
  '........PPPp..pPPP',
  '.......PPPP....PPPP',
  '.......PPPP....PPPP',
  '.......PPPP....PPPP',
  '.......PPP......PPP',
  '.......PPP......PPP',
  '.......PPP......PPP',
  '.......PPP......PPP',
  '.......DDD......DDD',
  '.......DDD......DDD',
  '......bbbb......bbbb',
  '.....bbbbb......bbbbb',
  '.....bbbbb......bbbbb',
];

const L_BRACE = [
  '.........PPPPPPPP',
  '.........PPPPPPPP',
  '.........PPPP.PPP',
  '........PPPP..PPPP',
  '........PPPP..PPPPP',
  '........PPPp..pPPPP',
  '.......PPPP....PPPP',
  '.......PPPP.....PPPP',
  '.......PPPP.....PPPP',
  '.......PPP.......PPP',
  '......PPPP.......PPP',
  '......PPPP.......PPP',
  '......PPP........PPP',
  '......DDD........DDD',
  '......DDD........DDD',
  '.....bbbb........bbbb',
  '....bbbbb........bbbbb',
  '....bbbbb........bbbbb',
];

const L_LUNGE = [
  '.........PPPPPPPP',
  '.........PPPPPPPP',
  '........PPPPPPPPPP',
  '.......PPPP...PPPPP',
  '......PPPP.....PPPPP',
  '.....PPPP.......PPPPP',
  '....PPPP.........PPPP',
  '....PPPp..........PPPP',
  '...PPPP...........PPPP',
  '...PPPP............PPP',
  '..PPPP.............PPP',
  '..PPP..............PPP',
  '..PPP..............PPP',
  '..DDD..............DDD',
  '..DDD..............DDD',
  '.bbbb..............bbbb',
  'bbbbb..............bbbbb',
  'bbbbb..............bbbbb',
];

const L_WALK1 = [
  '.........PPPPPPPP',
  '.........PPPPPPPP',
  '........PPPPPPPPP',
  '........PPPP.PPPP',
  '.......PPPP...PPPP',
  '.......PPPP...PPPPP',
  '......PPPP.....PPPP',
  '......PPPp.....pPPPP',
  '.....PPPP.......PPPP',
  '.....PPPP........PPP',
  '....PPPP.........PPP',
  '....PPP..........PPP',
  '....PPP..........PPP',
  '....DDD..........DDD',
  '....DDD..........DDD',
  '...bbbb..........bbbb',
  '..bbbbb..........bbbbb',
  '..bbbbb..........bbbbb',
];

const L_WALK2 = [
  '.........PPPPPPPP',
  '.........PPPPPPPP',
  '.........PPPPPPPP',
  '.........PPPP.PPPP',
  '.........PPPP.PPPP',
  '.........PPPp.PPPP',
  '.........PPPP..bbb',
  '.........PPPP..bbbb',
  '.........PPPP',
  '........PPPP',
  '........PPPP',
  '........PPP',
  '........PPP',
  '........DDD',
  '........DDD',
  '.......bbbb',
  '......bbbbb',
  '......bbbbb',
];

const L_WALK3 = [
  '.........PPPPPPPP',
  '.........PPPPPPPP',
  '........PPPPPPPPP',
  '........PPPP.PPPP',
  '.......PPPP...PPPP',
  '......PPPPP...PPPP',
  '......PPPP....PPPP',
  '.....pPPPP.....PPPp',
  '.....PPPP......PPPP',
  '.....PPP........PPPP',
  '.....PPP.........PPP',
  '.....PPP.........PPP',
  '.....PPP.........PPP',
  '.....DDD.........DDD',
  '.....DDD.........DDD',
  '....bbbb.........bbbb',
  '...bbbbb.........bbbbb',
  '...bbbbb.........bbbbb',
];

const L_WALK4 = [
  '.........PPPPPPPP',
  '.........PPPPPPPP',
  '.........PPPPPPPP',
  '........PPPP.PPPP',
  '........PPPP.PPPP',
  '........PPPp.PPPP',
  '........bbb..PPPP',
  '.......bbbb..PPPP',
  '.............PPPP',
  '.............PPPP',
  '............PPPP',
  '............PPP',
  '............PPP',
  '............DDD',
  '............DDD',
  '...........bbbb',
  '..........bbbbb',
  '..........bbbbb',
];

const F = (torso, legs, hd) => ({ a: 12, hi: true, hd: hd || [13, 2], r: torso.concat(legs) });

const BODY_FRAMES = {
  idle_a: F(T_GUARD, L_STAND),
  idle_b: F(T_GUARD_LO, L_STAND),
  idle_c: F(T_GUARD_HI, L_STAND),
  walk_a: F(T_GUARD, L_WALK1),
  walk_b: F(T_GUARD, L_WALK2),
  walk_c: F(T_GUARD, L_WALK3),
  walk_d: F(T_GUARD, L_WALK4),
  punch_wind: F(T_CHAMBER, L_BRACE),
  lpunch: F(T_PUNCH_MID, L_BRACE),
  hpunch: F(T_PUNCH_HI, L_LUNGE),
  punch_follow: F(T_PUNCH_FOLLOW, L_BRACE),
  throw_proj: F(T_THROW, L_LUNGE),
  block: F(T_BLOCK, L_STAND),
  hit: F(T_HIT, L_BRACE, [11, 2]),
  dazed: F(T_DAZED, L_STAND),
  win: F(T_WIN, L_STAND),
  win_b: F(T_WIN_B, L_STAND),
  upc_follow: F(T_PUNCH_FOLLOW, L_BRACE),

  jump: { a: 12, hi: true, hd: [13, 2], r: [
    '............DDD',
    '..........DDDDDDD',
    '.........DDDDDDDDD',
    '......DDDDDDDDDDDDD.SS',
    '.....SDDDPPPPPPPDD.SSS',
    '.....SDD.PPPPpPPDD.SS',
    '....SS...PPPPPPPPSS',
    '....SSS..PPPPpPPPSS',
    '.....SS..DPPPPPPD',
    '.........DDPPPPDD',
    '..........GGGGGG',
    '........PPPPPPPPP',
    '.......PPPPPPPPPPP',
    '.......PPPP...PPPP',
    '......PPPP....PPPP',
    '......PPPp....pPPP',
    '......bbbb....bbbb',
    '.....bbbbb....bbbbb',
  ]},

  jump_kick: { a: 12, hi: true, hd: [13, 2], r: [
    '............DDD',
    '..........DDDDDDD',
    '.........DDDDDDDDD',
    '......DDDDDDDDDDDDD.SS',
    '.....SDDDPPPPPPPDD.SSS',
    '.....SDD.PPPPpPPDD.SS',
    '....SS...PPPPPPPPSS',
    '....SSS..PPPPpPPPSS',
    '.....SS..DPPPPPPD',
    '.........DDPPPPDDPPP',
    '..........GGGGGGPPPP',
    '........PPPPPPPPPPPPP',
    '.......PPPPPP...PPPPPP',
    '.......PPPP.......PPPPbb',
    '......PPPP.........bbbbb',
    '......PPPp..........bbbb',
    '......bbbb',
    '.....bbbbb',
  ]},

  crouch: { a: 12, hi: true, hd: [13, 2], r: [
    '............DDD',
    '..........DDDDDDD',
    '.........DDDDDDDDDD',
    '.......DDDDDDDDDDDD.SS',
    '......SDDDPPPPPPPDD.SSS',
    '.....SSDD.PPPPpPPDD.SS',
    '.....SS...PPPPPPPPSS',
    '.....SS...DPPPPpPPSS',
    '......S...DDPPPPPD',
    '..........GGGGGGG',
    '........PPPPPPPPPPP',
    '......PPPPPPPPPPPPPP',
    '.....PPPPp......pPPPP',
    '.....PPPP........PPPP',
    '....bbbbb........bbbbb',
    '....bbbbb........bbbbb',
  ]},

  crouch_punch: { a: 12, hi: true, hd: [13, 2], r: [
    '............DDD',
    '..........DDDDDDD',
    '.........DDDDDDDDDD',
    '.......DDDDDDDDDDDD',
    '......SDDDPPPPPPPDD',
    '.....SSDD.PPPPpPPDD',
    '.....SS...PPPPPPPPSSSSSSSSSS',
    '.....SS...DPPPPpPPSSSSSSSSSS',
    '......S...DDPPPPPD',
    '..........GGGGGGG',
    '........PPPPPPPPPPP',
    '......PPPPPPPPPPPPPP',
    '.....PPPPp......pPPPP',
    '.....PPPP........PPPP',
    '....bbbbb........bbbbb',
    '....bbbbb........bbbbb',
  ]},

  crouch_kick: { a: 12, hi: true, hd: [13, 2], r: [
    '............DDD',
    '..........DDDDDDD',
    '.........DDDDDDDDDD',
    '.......DDDDDDDDDDDD.SS',
    '......SDDDPPPPPPPDD.SSS',
    '.....SSDD.PPPPpPPDD.SS',
    '.....SS...PPPPPPPPSS',
    '.....SS...DPPPPpPPSS',
    '......S...DDPPPPPD',
    '..........GGGGGGG',
    '........PPPPPPPPPPP',
    '......PPPPPPPPPPPPPPPPPPP',
    '.....PPPPp....PPPPPPPPPPbbbb',
    '.....PPPP.............bbbb',
    '....bbbbb',
    '....bbbbb',
  ]},

  block_crouch: { a: 12, hi: true, hd: [13, 2], r: [
    '............DDD',
    '..........DDDDDDD',
    '.........DDDDDDDDDD',
    '.......DDDDDDDDDDDD',
    '......SDDPSSSSSPDDD',
    '.....SSD.SSSSSSSDD',
    '.....SS..SSSSSSSS',
    '.....SS..DPSSSSPP',
    '......S...DDPPPPPD',
    '..........GGGGGGG',
    '........PPPPPPPPPPP',
    '......PPPPPPPPPPPPPP',
    '.....PPPPp......pPPPP',
    '.....PPPP........PPPP',
    '....bbbbb........bbbbb',
    '....bbbbb........bbbbb',
  ]},

  upc_wind: { a: 12, hi: true, hd: [13, 2], r: [
    '............DDD',
    '..........DDDDDDD',
    '.........DDDDDDDDDD',
    '.......DDDDDDDDDDDD',
    '......SDDDPPPPPPPDD',
    '.....SSDD.PPPPpPPDD',
    '....SS....PPPPPPPP',
    '...SS.....DPPPPpPP',
    '...SS.....DDPPPPPD',
    '..SSS.....GGGGGGG',
    '........PPPPPPPPPPP',
    '......PPPPPPPPPPPPPP',
    '.....PPPPp......pPPPP',
    '.....PPPP........PPPP',
    '....bbbbb........bbbbb',
    '....bbbbb........bbbbb',
  ]},

  upc_hit: { a: 12, hi: true, hd: [12, 9], r: [
    '..................SSS',
    '..................SSS',
    '..................SS',
    '.................SSS',
    '.................SS',
    '................SSS',
    '............DDDSSS',
    '..........DDDDDDDDD',
    '.........DDDDDDDDDD',
    '......DDDDPPPPPPDD',
    '.....SDDDPPPPPPPDD',
    '.....SDD.PPPPpPPD',
    '....SS...PPPPPPPP',
    '....SS...PPPPpPPP',
    '....SS...DPPPPPPD',
    '.....SS..DDPPPPDD',
    '..........GGGGGG',
  ].concat(L_STAND)},

  kick_wind: { a: 12, hi: true, hd: [13, 2], r: T_GUARD.concat([
    '.........PPPPPPPP',
    '.........PPPPPPPP',
    '.........PPPP.PPPP',
    '.........PPPP.PPPPP',
    '.........PPPP.pPPPP',
    '.........PPPp..bbbb',
    '.........PPPP..bbbbb',
    '........PPPP',
    '........PPPP',
    '........PPP',
    '........PPP',
    '........PPP',
    '........PPP',
    '........DDD',
    '........DDD',
    '.......bbbb',
    '......bbbbb',
    '......bbbbb',
  ])},

  hkick: { a: 12, hi: true, hd: [11, 2], r: [
    '..........DDD',
    '.........DDDDDDD',
    '........DDDDDDDDD',
    '......DDDDDDDDDDDD',
    '.....SDDDPPPPPPDDD',
    '....SSDDDPPPPPPPDD......bbbb',
    '....SS.D.PPPPpPPDD....bbbbbb',
    '...SS....PPPPPPPP...PPPP',
    '...SS....PPPPpPPP.PPPP',
    '...SS....DPPPPPPDPPPP',
    '...SS....DPPPPPPPPPP',
    '....SS...DDPPPPPPPP',
    '.........GGGGGGG',
    '........PPPPPPPP',
    '........PPPP',
    '........PPPP',
    '........PPPP',
    '........PPP',
    '........PPP',
    '........PPP',
    '........PPP',
    '........DDD',
    '........DDD',
    '.......bbbb',
    '......bbbbb',
    '......bbbbb',
  ]},

  lkick: { a: 12, hi: true, hd: [13, 2], r: T_GUARD.concat([
    '........PPPPPPPPPPPPPPPPP',
    '........PPPPPPPPPPPPPPPPPbbbb',
    '........PPPPPPPPPPPPPPPPPbbbb',
    '........PPPP',
    '........PPPP',
    '........PPP',
    '........PPP',
    '........PPP',
    '........DDD',
    '........DDD',
    '.......bbbb',
    '......bbbbb',
    '......bbbbb',
  ])},

  kick_follow: { a: 12, hi: true, hd: [13, 2], r: T_GUARD.concat([
    '........PPPPPPPPPP',
    '........PPPP..PPPPPP',
    '........PPPP....PPPPbb',
    '........PPPP.....bbbbb',
    '........PPPP',
    '........PPP',
    '........PPP',
    '........PPP',
    '........DDD',
    '........DDD',
    '.......bbbb',
    '......bbbbb',
    '......bbbbb',
  ])},

  sweep: { a: 10, hi: true, hd: [11, 2], r: [
    '..........DDD',
    '.........DDDDDDD',
    '........DDDDDDDDDD',
    '......SDDDDDDDDDDD',
    '.....SSDDPPPPPPPDD',
    '.....SS..PPPPpPPDD',
    '......S..PPPPPPPP',
    '..........GGGGGG',
    '.......PPPPPPPPPP',
    '.....PPPPPP...PPPPPPPPPPPPP',
    '....PPPPP........PPPPPPPPPPbbbb',
    '....bbbbb..................bbbb',
    '...bbbbbb',
  ]},

  // ---- airborne / floored: integrated head (identity via palette) ----
  juggle: { a: 15, hi: true, noHead: true, r: [
    '......SSS.........bbbb',
    '.......SSS......bbbbb',
    '..HHH...DDDPPPPPPPP',
    '.HHHHH.DDPPPPPPPPPPPP',
    '.HHHHHHDPPPPpPPPPPPPPP',
    '.HHHHH.DPPPPPPPP.GGG',
    '..SSS..PPPPPPPP...PPPP',
    '.......SS.....SS...PPPPbb',
    '...............SS...bbbbb',
  ]},

  down: { a: 15, hi: true, noHead: true, r: [
    '...........DDDD',
    '..HHHHH.DDDDPPPPPPPPPPPPPPbbbb',
    '.HHHHHHHDDPPPPPPPpPPPPPPPPbbbb',
    '.HHSSHHH.GGGGPPPPPPPPPP',
    '..HHHHH',
  ]},

  torpedo: { a: 15, hi: true, noHead: true, r: [
    '...bbbb.DDDDDDDDHHHH',
    '..bbbbbPPPPPPPPPHHHHHH.SSSS',
    '..bbbbPPPPPpPPPPHSSHHHSSSSS',
    '.......PPPPPPPPPHHHHHH.SSSS',
    '........GGG.....HHHH',
    '.',
    '.',
    '.',
    '.',
    '.',
  ]},
};

const FIGHTER_FRAME_KEYS = Object.keys(BODY_FRAMES);

// ---- character heads (facing right, anchored bottom-center) ----
const HEAD_ART = {
  kiro: { r: [
    '....HHHHHH',
    '..HHHHHHHHH',
    '.HHHHHHHHHHH',
    '.HHHHHHHHHHH',
    '.HHHHHHHHHHH',
    '.HHSSSSSSSHH',
    '.HHSWWkSWWkH',
    '.HHMMMMMMMMH',
    '..HMMMMMMMMM',
    '..HHMMMMMMMM',
    '...HHMMMMMM',
  ]},
  ashkar: { r: [
    '....HHHHHH',
    '..HHHHHHHHH',
    '.HHHHHHHHHHH',
    '.HHHHHHHHHHH',
    '.HHHHHHHHHHH',
    '.HHSSSSSSSHH',
    '.HHSWWkSWWkH',
    '.HHMMMMMMMMH',
    '..Hmmmmmmmmm',
    '...HHMMMMMM',
    '....HHmmmm',
  ]},
  voltan: { r: [
    '.......TT',
    '......TTTT',
    '.TTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTT',
    '...dddddddddd',
    '...ddWWdWWddd',
    '...SSSSSSSSS',
    '...SBBBBBBBS',
    '...BBBBBBBBBB',
    '....BBBBBBBB',
    '.....BBBBB',
  ]},
  striker: { r: [
    '...KKKKKK',
    '..KKKKKKKKK',
    '..KKKKKKKKK',
    '..BBBBBBBBB',
    '..SSSSSSSSS',
    '..SWWkSWWkS',
    '..CCCCCCCCC',
    '..CCcCCCcCC',
    '..CCCCCCCCC',
    '...CCCCCCCC',
    '....CCCCC',
  ]},
};

// Build a character's full frame set: body poses + their head.
function buildFighterFrames(charId) {
  const head = HEAD_ART[charId];
  const out = {};
  for (const k in BODY_FRAMES) {
    const b = BODY_FRAMES[k];
    out[k] = (b.noHead || !head) ? b : compositeFrame(b, head);
  }
  return out;
}
